export const fallbackAnalysis = {
  documentTitle: "Attention Is All You Need",
  sourceFilename: "attention-is-all-you-need.pdf",
  pdfUrl: "/uploads/attention-is-all-you-need.pdf",
  pageCount: 15,
  language: "en",
  status: "fallback",
  variables: [
    { id: "q", symbol: "Q", name: "Query matrix", type: "Matrix", unit: "-", role: "Attention input", meaning: "Represents the queries used to retrieve relevant information from keys.", memory: "What each token is asking for.", source: "Demo paper", formulas: ["f1", "f2"], anchors: ["p.4: We compute attention as a function of queries, keys and values."] },
    { id: "k", symbol: "K", name: "Key matrix", type: "Matrix", unit: "-", role: "Attention input", meaning: "Encodes the indexable content against which queries are matched.", memory: "What each token can be matched against.", source: "Demo paper", formulas: ["f1", "f2"], anchors: ["p.4: Queries are packed together into a matrix Q, keys into K and values into V."] },
    { id: "v", symbol: "V", name: "Value matrix", type: "Matrix", unit: "-", role: "Attention input", meaning: "Carries the content mixed according to the attention weights.", memory: "The information that actually gets blended.", source: "Demo paper", formulas: ["f1", "f2"], anchors: ["p.4: Values are packed together into a matrix V."] },
    { id: "dk", symbol: "d_k", name: "Key dimension", type: "Scalar", unit: "-", role: "Scaling factor", meaning: "Dimensionality of keys used to scale dot products before softmax.", memory: "The square-root divisor that keeps scores stable.", source: "Demo paper", formulas: ["f1"], anchors: ["p.4: We scale the dot products by 1/sqrt(d_k)."] },
    { id: "head", symbol: "head_i", name: "Attention head", type: "Matrix", unit: "-", role: "Intermediate tensor", meaning: "One parallel attention branch in multi-head attention.", memory: "A single attention lane before concatenation.", source: "Demo paper", formulas: ["f2"], anchors: ["p.5: Where head_i = Attention(QW_i^Q, KW_i^K, VW_i^V)."] },
    { id: "wo", symbol: "W^O", name: "Output projection", type: "Matrix", unit: "-", role: "Projection matrix", meaning: "Projects concatenated attention heads back into model space.", memory: "The layer that mixes all heads back together.", source: "Demo paper", formulas: ["f2"], anchors: ["p.5: MultiHead(Q, K, V) = Concat(head_1, ..., head_h)W^O."] },
    { id: "x", symbol: "x", name: "Position-wise input", type: "Vector", unit: "-", role: "Layer input", meaning: "Input vector passed into the feed-forward network.", memory: "What enters the FFN block at each position.", source: "Demo paper", formulas: ["f3"], anchors: ["p.5: FFN(x) = max(0, xW_1 + b_1)W_2 + b_2."] },
    { id: "w1", symbol: "W_1", name: "First FFN weight", type: "Matrix", unit: "-", role: "Projection matrix", meaning: "Expands the representation in the first linear layer of the FFN.", memory: "The first learned expansion step.", source: "Demo paper", formulas: ["f3"], anchors: [] },
    { id: "w2", symbol: "W_2", name: "Second FFN weight", type: "Matrix", unit: "-", role: "Projection matrix", meaning: "Projects the activated hidden vector back to model dimension.", memory: "The return path from FFN hidden space.", source: "Demo paper", formulas: ["f3"], anchors: [] },
    { id: "b1", symbol: "b_1", name: "First bias", type: "Vector", unit: "-", role: "Bias term", meaning: "Bias added before the ReLU activation.", memory: "Shift before the nonlinearity.", source: "Demo paper", formulas: ["f3"], anchors: [] },
    { id: "b2", symbol: "b_2", name: "Second bias", type: "Vector", unit: "-", role: "Bias term", meaning: "Bias added after the second FFN projection.", memory: "Final offset after projection.", source: "Demo paper", formulas: ["f3"], anchors: [] },
    { id: "lrate", symbol: "lrate", name: "Learning rate", type: "Scalar", unit: "-", role: "Optimization schedule", meaning: "Transformer learning-rate schedule with warmup and inverse square-root decay.", memory: "Warm up early, decay slowly later.", source: "Demo paper", formulas: ["f4"], anchors: ["p.7: lrate = d_model^-0.5 * min(step_num^-0.5, step_num * warmup_steps^-1.5)."] },
    { id: "dmodel", symbol: "d_{model}", name: "Model dimension", type: "Scalar", unit: "-", role: "Architecture hyperparameter", meaning: "The shared representation width used across the Transformer.", memory: "The main hidden width of the model.", source: "Demo paper", formulas: ["f4"], anchors: [] },
    { id: "step", symbol: "step_{num}", name: "Training step", type: "Scalar", unit: "step", role: "Optimization counter", meaning: "Current update count used in the learning-rate schedule.", memory: "Where training currently is on the schedule.", source: "Demo paper", formulas: ["f4"], anchors: [] },
    { id: "warmup", symbol: "warmup_{steps}", name: "Warmup steps", type: "Scalar", unit: "step", role: "Optimization hyperparameter", meaning: "Number of steps used for linear warmup before decay.", memory: "How long the ramp-up lasts.", source: "Demo paper", formulas: ["f4"], anchors: [] },
  ],
  formulas: [
    {
      id: "f1",
      title: "Scaled dot-product attention",
      expression: "Attention(Q,K,V)=softmax(QK^T/\\sqrt{d_k})V",
      physicalMeaning: "Computes attention weights from query-key similarity and uses them to mix values.",
      memory: "Match queries to keys, normalize, then blend values.",
      output: null,
      page: 4,
      bbox: { x0: 0.14, y0: 0.28, x1: 0.86, y1: 0.36 },
      sourceCandidateId: "demo-f1",
      semantic: { lhsSymbols: ["Attention"], rhsSymbols: ["Q", "K", "V", "d_k"], operators: ["=", "/", "^"], complexity: 7 },
      inputs: ["q", "k", "v", "dk"],
      dependsOn: [],
      paperNote: "Section 3.2.1",
      anchors: ["p.4: Attention(Q, K, V) = softmax(QK^T / sqrt(d_k))V."],
      chunks: [{ label: "Attention core", text: "Query-key scores are scaled, normalized by softmax, and applied to values.", variableIds: ["q", "k", "v", "dk"] }],
    },
    {
      id: "f2",
      title: "Multi-head attention",
      expression: "MultiHead(Q,K,V)=Concat(head_1,\\ldots,head_h)W^O",
      physicalMeaning: "Runs several attention heads in parallel and projects their concatenation.",
      memory: "Many attention lanes, one shared output projection.",
      output: null,
      page: 5,
      bbox: { x0: 0.16, y0: 0.23, x1: 0.88, y1: 0.30 },
      sourceCandidateId: "demo-f2",
      semantic: { lhsSymbols: ["MultiHead"], rhsSymbols: ["Q", "K", "V", "head_i", "W^O"], operators: ["="], complexity: 6 },
      inputs: ["q", "k", "v", "head", "wo"],
      dependsOn: ["f1"],
      paperNote: "Section 3.2.2",
      anchors: ["p.5: MultiHead(Q, K, V) = Concat(head_1, ..., head_h)W^O."],
      chunks: [{ label: "Head merge", text: "Parallel heads are concatenated and projected with W^O.", variableIds: ["head", "wo", "q", "k", "v"] }],
    },
    {
      id: "f3",
      title: "Position-wise feed-forward network",
      expression: "FFN(x)=\\max(0,xW_1+b_1)W_2+b_2",
      physicalMeaning: "Applies the same two-layer feed-forward network independently at each position.",
      memory: "Expand, activate, then project back.",
      output: null,
      page: 5,
      bbox: { x0: 0.14, y0: 0.55, x1: 0.82, y1: 0.62 },
      sourceCandidateId: "demo-f3",
      semantic: { lhsSymbols: ["FFN"], rhsSymbols: ["x", "W_1", "b_1", "W_2", "b_2"], operators: ["=", "+", "*"], complexity: 8 },
      inputs: ["x", "w1", "b1", "w2", "b2"],
      dependsOn: [],
      paperNote: "Section 3.3",
      anchors: ["p.5: FFN(x) = max(0, xW_1 + b_1)W_2 + b_2."],
      chunks: [{ label: "FFN block", text: "A point-wise MLP with ReLU between two learned affine transforms.", variableIds: ["x", "w1", "b1", "w2", "b2"] }],
    },
    {
      id: "f4",
      title: "Learning-rate schedule",
      expression: "lrate=d_{model}^{-0.5}\\min(step_{num}^{-0.5},step_{num}warmup_{steps}^{-1.5})",
      physicalMeaning: "Warmup schedule that increases learning rate early and decays it later.",
      memory: "Scale by model width, then choose the smaller warmup/decay branch.",
      output: "lrate",
      page: 7,
      bbox: { x0: 0.18, y0: 0.36, x1: 0.84, y1: 0.44 },
      sourceCandidateId: "demo-f4",
      semantic: { lhsSymbols: ["lrate"], rhsSymbols: ["d_{model}", "step_{num}", "warmup_{steps}"], operators: ["=", "^"], complexity: 7 },
      inputs: ["lrate", "dmodel", "step", "warmup"],
      dependsOn: [],
      paperNote: "Section 5.3",
      anchors: ["p.7: This corresponds to increasing the learning rate linearly for the first warmup_steps training steps, and decreasing it thereafter proportionally to the inverse square root of the step number."],
      chunks: [{ label: "Schedule", text: "The schedule combines model-size scaling, warmup, and inverse-square-root decay.", variableIds: ["lrate", "dmodel", "step", "warmup"] }],
    },
  ],
  documentInsight: {
    overview: "A real demo PDF is loaded by default. Upload another paper to replace this graph with a task-based background analysis.",
    pipeline: [
      "Upload returns a task id immediately and starts the parser asynchronously.",
      "PyMuPDF builds the first visible graph before any heavy enhancement finishes.",
      "Nougat runs only in the background and is skipped automatically for long PDFs or quick mode.",
    ],
  },
  extractedText: "",
  formulaCandidates: [],
  warnings: ["Demo mode is active until you upload a new PDF."],
};
