export const variables = [
  {
    id: "u",
    symbol: "u_t",
    name: "Grid energy price",
    type: "Scalar",
    unit: "USD / kWh",
    role: "Exogenous parameter",
    meaning: "Time-dependent unit price paid to purchase electricity from the grid.",
    memory: "Think of it as the tariff sticker attached to every imported kilowatt-hour.",
    source: "Observed market data",
    formulas: ["f1", "f5"],
  },
  {
    id: "q",
    symbol: "q_t",
    name: "Purchased electricity",
    type: "Decision variable",
    unit: "kWh",
    role: "Control variable",
    meaning: "Amount of electricity imported from the external grid at time t.",
    memory: "The system decides how much energy to buy right now.",
    source: "Optimized by solver",
    formulas: ["f1", "f2", "f5"],
  },
  {
    id: "p",
    symbol: "p_t",
    name: "Renewable generation",
    type: "Vector element",
    unit: "kWh",
    role: "Process variable",
    meaning: "Renewable power available during the current time slice.",
    memory: "Free energy arriving from the environment.",
    source: "Forecast model",
    formulas: ["f2"],
  },
  {
    id: "d",
    symbol: "d_t",
    name: "Demand",
    type: "Vector element",
    unit: "kWh",
    role: "Target variable",
    meaning: "Load that must be satisfied in the current time step.",
    memory: "What the system must serve no matter what.",
    source: "Observed load",
    formulas: ["f2"],
  },
  {
    id: "s",
    symbol: "s_t",
    name: "Battery state",
    type: "State variable",
    unit: "kWh",
    role: "State variable",
    meaning: "Energy stored in the battery at time t.",
    memory: "A snapshot of how much charge is left in the tank.",
    source: "Updated recursively",
    formulas: ["f3", "f4"],
  },
  {
    id: "c",
    symbol: "c_t",
    name: "Charging power",
    type: "Decision variable",
    unit: "kWh",
    role: "Control variable",
    meaning: "Amount of energy pushed into the battery during the time step.",
    memory: "The charging pedal.",
    source: "Optimized by solver",
    formulas: ["f3", "f4"],
  },
  {
    id: "r",
    symbol: "r_t",
    name: "Discharging power",
    type: "Decision variable",
    unit: "kWh",
    role: "Control variable",
    meaning: "Amount of energy drawn from the battery during the time step.",
    memory: "The discharging pedal.",
    source: "Optimized by solver",
    formulas: ["f3", "f4"],
  },
  {
    id: "eta",
    symbol: "η",
    name: "Battery efficiency",
    type: "Scalar",
    unit: "-",
    role: "Hyperparameter",
    meaning: "Round-trip efficiency coefficient used in charge and discharge calculations.",
    memory: "How much energy survives the battery trip.",
    source: "System specification",
    formulas: ["f3"],
  },
  {
    id: "e",
    symbol: "E_t",
    name: "Economic cost",
    type: "Scalar",
    unit: "USD",
    role: "Objective term",
    meaning: "Monetary cost of buying electricity from the grid.",
    memory: "Price times amount.",
    source: "Derived quantity",
    formulas: ["f1", "f6"],
  },
  {
    id: "j",
    symbol: "J",
    name: "Total objective",
    type: "Scalar",
    unit: "USD",
    role: "Optimization target",
    meaning: "Overall objective minimized by the scheduling problem.",
    memory: "The scoreboard for the whole optimization.",
    source: "Aggregated quantity",
    formulas: ["f6"],
  },
];

export const formulas = [
  {
    id: "f1",
    title: "Economic cost",
    expression: "E_t = u_t × q_t",
    physicalMeaning: "The direct monetary payment for imported electricity in one time slice.",
    memory: "A classic price × quantity block.",
    output: "e",
    inputs: ["u", "q"],
    dependsOn: [],
    paperNote: "Section 3.2, objective decomposition",
    chunks: [
      {
        label: "Price term",
        text: "u_t captures the tariff applied to each purchased unit of electricity.",
        variableIds: ["u"],
      },
      {
        label: "Purchase term",
        text: "q_t is the optimization decision that determines how much electricity is imported.",
        variableIds: ["q"],
      },
      {
        label: "Economic block",
        text: "Multiplying the two terms converts operational choice into a monetary penalty.",
        variableIds: ["u", "q", "e"],
      },
    ],
  },
  {
    id: "f2",
    title: "Power balance",
    expression: "q_t + p_t + r_t = d_t + c_t",
    physicalMeaning: "Supply entering the node must match the load plus the charging sink.",
    memory: "Everything coming in must be accounted for.",
    output: null,
    inputs: ["q", "p", "r", "d", "c"],
    dependsOn: [],
    paperNote: "Section 2.1, system constraints",
    chunks: [
      {
        label: "Supply side",
        text: "Grid purchases, renewables, and battery discharge contribute available energy.",
        variableIds: ["q", "p", "r"],
      },
      {
        label: "Demand side",
        text: "Load demand and battery charging consume the available supply.",
        variableIds: ["d", "c"],
      },
    ],
  },
  {
    id: "f3",
    title: "State transition",
    expression: "s_(t+1) = s_t + η × c_t - r_t / η",
    physicalMeaning: "Battery state evolves based on efficient charging and lossy discharging.",
    memory: "Charge adds, discharge subtracts, and efficiency bends both flows.",
    output: "s",
    inputs: ["s", "eta", "c", "r"],
    dependsOn: ["f2"],
    paperNote: "Section 2.2, battery dynamics",
    chunks: [
      {
        label: "Initial state",
        text: "s_t provides the current energy stored before the new action is applied.",
        variableIds: ["s"],
      },
      {
        label: "Charging gain",
        text: "η × c_t means only the efficient fraction of charging power becomes stored energy.",
        variableIds: ["eta", "c"],
      },
      {
        label: "Discharging loss",
        text: "r_t / η models that more stored energy is consumed than the delivered output.",
        variableIds: ["eta", "r"],
      },
    ],
  },
  {
    id: "f4",
    title: "Battery safety",
    expression: "0 ≤ s_t + c_t - r_t ≤ S_max",
    physicalMeaning: "The battery cannot exceed its physical capacity or go below zero.",
    memory: "The state must stay inside the tank walls.",
    output: null,
    inputs: ["s", "c", "r"],
    dependsOn: ["f3"],
    paperNote: "Section 2.2, operational limits",
    chunks: [
      {
        label: "Feasibility window",
        text: "The intermediate state after charge and discharge must remain bounded.",
        variableIds: ["s", "c", "r"],
      },
    ],
  },
  {
    id: "f5",
    title: "Marginal sensitivity",
    expression: "∂E_t / ∂q_t = u_t",
    physicalMeaning: "The marginal cost of purchasing one more unit equals the market price.",
    memory: "The slope of the cost curve is just the tariff.",
    output: null,
    inputs: ["e", "q", "u"],
    dependsOn: ["f1"],
    paperNote: "Section 3.3, economic interpretation",
    chunks: [
      {
        label: "Derivative target",
        text: "We inspect how economic cost changes as purchase quantity changes.",
        variableIds: ["e", "q"],
      },
      {
        label: "Sensitivity result",
        text: "Because the original cost is linear, the derivative collapses to the price term u_t.",
        variableIds: ["u"],
      },
    ],
  },
  {
    id: "f6",
    title: "Total objective",
    expression: "J = Σ_t E_t + λ · degradation",
    physicalMeaning: "The final optimization target combines direct electricity payments and wear penalties.",
    memory: "A weighted total score over the whole horizon.",
    output: "j",
    inputs: ["e", "j"],
    dependsOn: ["f1", "f4"],
    paperNote: "Section 3.4, final objective",
    chunks: [
      {
        label: "Economic accumulation",
        text: "Summing E_t over time converts local costs into a horizon-wide objective term.",
        variableIds: ["e"],
      },
      {
        label: "Penalty coupling",
        text: "A regularization term discourages aggressive battery usage that would accelerate degradation.",
        variableIds: ["j"],
      },
    ],
  },
];

export const documentInsight = {
  overview:
    "This prototype reconstructs a mock energy scheduling paper into a graph-centric reading experience. Each formula becomes an explorable knowledge card with variable bindings, explanation chunks, and graph dependencies.",
  pipeline: [
    "PDF parsing layer: reserved for text blocks and formula boundary extraction.",
    "Semantic layer: reserved for LLM-produced JSON containing symbols, chunks, and topology.",
    "Visualization layer: implemented here as an interactive single-page UI.",
  ],
};
